apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../operators/authorino-operator/operator/overlays/managed-services
  - ../../../operators/openshift-pipelines-operator-rh/operator/overlays/latest
  - ../../../operators/rhods-operator/operator/overlays/fast
  - ../../../operators/rhods-operator/instance/overlays/2.9.1
  - ../../../operators/serverless-operator/operator/overlays/stable
  - ../../../operators/servicemeshoperator/operator/overlays/stable

  # service mesh optional
  # - ../../../../components/operators/kiali-ossm/operator/overlays/stable
